### ISSUE TITLE
Publication on F-Droid

### ISSUE THREAD

**Issue by valerio-bozzolan** [ferdi2005/monumenti#7]
Let's publish this awesome app on F-Droid.

Requirements:

* [ ] a clean directory where you can run `gradle assembleDebug` without a failure (that is your `subdir`)
* [ ] F-Droid metadata in Yaml · [F-Droid metadata documentation](https://f-droid.org/en/docs/Build_Metadata_Reference/)

Example metadata:

* https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/it.reyboz.bustorino.yml

Stub metadata:

https://gist.github.com/valerio-bozzolan/42b25eeb7fafb4f6e94dd0bade56a5c8

**Comment by ferdi2005** [comment]
Nice proposal! This is an updated metadata, let's wait for the 2.0.0 release (it's coming really soon).

```
Categories:
  - Navigation
License: GPL-3.0-or-later
AuthorName: Ferdinando Traversa
AuthorEmail: REDACTED
WebSite: https://cerca.wikilovesmonuments.it
SourceCode: https://github.com/ferdi2005/monumenti
IssueTracker: https://github.com/ferdi2005/monumenti/issues
AntiFeatures: 
- Tracking
AutoName: WikiLovesMonuments Italia

RepoType: git
Repo: https://github.com/ferdi2005/monumenti

Builds:
  - subdir: build/android/
  - versionCode: 19
  - commit: 'v2.0.0'

AutoUpdateMode: Version %v
UpdateCheckMode: Tags
CurrentVersion: 2.0.0
CurrentVersionCode: 19
```
